### ISSUE TITLE
Recommanded distance to board edge

### ISSUE THREAD

**Issue by X-Ryl669** [SimonMerrett/SOICbite#16]
I'm finally trying to implement this footprint on one of my board, and I'm wondering what is the best expected distance from board edge ?

In the connector footprint, there's an inverted T on the bottom, but I just wanted to be sure it's meaning it's supposed to match the board edge:
![image](https://user-images.githubusercontent.com/3277165/83571545-469a1780-a528-11ea-9d6a-ba15493d79d9.png)

Can you confirm ?

**Comment by SimonMerrett** [comment]
Yes, that lower "baseline" in the image is supposed to be a guide to line up with the board edge. You could place it further into the board (limited by the "throat" of your clip) but this is probably the best compromise between being unobtrusive and relatively stable when the clip is connected.

**Comment by SimonMerrett** [comment]
![image](https://github.com/SimonMerrett/SOICbite/blob/master/images/Unchecked%20Dimensional%20Drawing.PNG)

**Comment by X-Ryl669** [comment]
Thanks! Very useful.
